apiVersion: v1
kind: Pod
metadata:
  name: input
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: pool-1
  containers:
  - name: input
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - |
        echo "reading file from input volume..."
        cat /tmp/input/some-file
        sleep 999h
    volumeMounts:
      - name: input-vol
        mountPath: /tmp/input
  volumes:
    - name: input-vol
      persistentVolumeClaim:
        claimName: artifact-input
